n= input('Digite Algo: ')
print('O tipo primitivo deste valor é: ', type(n))
print('é numero? ', n.isnumeric())
print('é alphanumerico? ', n.isalnum())
print('é alfabético? ' , n.isalpha())
print('é decimal? ', n.isdecimal())
print('é um digito? ', n.isdigit())
print('é minusculo? ', n.islower())
print('é um espaço? ', n.isspace())
print('está capitalizada? ', n.istitle())
print('é maiusculo? ', n.isupper())
